### ISSUE TITLE
error in skipchars(BufferedInputStream)

### ISSUE THREAD

**Issue by denius** [JuliaIO/BufferedStreams.jl#57]
Hello!
I'm trying to parse a buffered file, but
```
skipchars(isspace, BufferedInputStream(IOBuffer(" test")))
```
yields ```ERROR: ArgumentError: n must be non-negative in skip(::BufferedInputStream, n)``` due to
https://github.com/BioJulia/BufferedStreams.jl/blob/b85ff82efcd95d3a4d72a4021f0833b579554bec/src/bufferedinputstream.jl#L126 which is different from [Julia/base/iobuffer.jl](https://github.com/JuliaLang/julia/blob/dc3056bebfc661e658f7e97913ccceda2737cb8c/base/iobuffer.jl#L235)

**Comment by JeffBezanson** [comment]
It would be very useful to implement negative skip amounts, since that allows using a buffered stream as a drop-in replacement in more cases. For example in https://github.com/JuliaLang/julia/issues/34195 this would be needed for BufferedStreams to work with SeisIO.

**Comment by stevengj** [comment]
In the meantime it would be even easier to implement `skipchars`.
