### ISSUE TITLE
transfer to JuliaIO?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaIO/BufferedStreams.jl#61]
I think it would make sense to move this over to JuliaIO along with TranscodingStreams and all the CodecX packages.

**Comment by kescobo** [comment]
I'm in favor, for sure, but I think @bicycle1885 is probably best suited to comment.

Can you find someone to take on Yaml.jl while you're at it 😆 ?

**Comment by StefanKarpinski** [comment]
> Can you find someone to take on Yaml.jl while you're at it 😆 ?

Sure! Seems like https://github.com/JuliaData would be a good home for it. Anyone a member of both and able to do the transfer? I'm not in either org, so I'm just a bystander here 😬

**Comment by kescobo** [comment]
Alright, it is done!
