### ISSUE TITLE
Some links point to BioJulia instead of JuliaIO

### ISSUE THREAD

**Issue by rben01** [JuliaIO/BufferedStreams.jl#73]
Some links broke when this package was moved from BioJulia to JuliaIO. For instance, the badges on this page: https://juliapackages.com/p/bufferedstreams

**Comment by kescobo** [comment]
I'm not sure that juliapackages.com is being updated. I think the preferred source for this kind of thing is juliahub, though I just checked, and they're still linking to BioJulia as well https://juliahub.com/ui/Packages/BufferedStreams/wMWKi/1.1.0

The good news is that any links to the actual github repo get redirected here, but there's a link to the docs that goes to biojulia.dev that doesn't work.
